use_frameworks!

platform :ios, '11.0'

target 'SwiftyFileBrowser_Example' do
  pod 'SwiftyFileBrowser', :path => '../'
  pod 'NFDownloadButton', :git => 'https://github.com/ghostlordstar/NFDownloadButton.git',  :branch => 'master'
end
