use_frameworks!

platform :ios, '10.0'

target 'SwiftyFileBrowser_Example' do
  pod 'SwiftyFileBrowser', :path => '../'

  target 'SwiftyFileBrowser_Tests' do
    inherit! :search_paths

    
  end
end
